### ISSUE TITLE
bower

### ISSUE THREAD

**Issue by TrySound** [finom/matreshka#11]
Change please bower main to non-minified version

**Comment by finom** [comment]
@TrySound why do you need this?

**Comment by TrySound** [comment]
Because it still will uglified by builder. And it is usual.

**Comment by finom** [comment]
Do you think everybody who uses bower uses uglifier? I'm not sure.

**Comment by TrySound** [comment]
If they use main field, yes)

**Comment by finom** [comment]
K. Done.

**Comment by TrySound** [comment]
Thank you, Andrey:)
