### ISSUE TITLE
Матрешке нужен es5-sham.min.js ?

### ISSUE THREAD

**Issue by Mausglov** [finom/matreshka#15]
В документации сказано: для поддержки IE8 подключите файл из [es5-shim](https://github.com/es-shims/es5-shim). Но там 2 файла: 

* es5-shim.min.js - обязательный файл
* es5-sham.min.js - какие-то добавки ( [прямая ссылка в ридми](https://github.com/es-shims/es5-shim#shams) )

Нужен ли этот второй файл для Матрёшки?

**Comment by finom** [comment]
No, it's not needed.
