### ISSUE TITLE
MK.Array#rerender() doesn't rerenders nodes from scratch

### ISSUE THREAD

**Issue by atnartur** [finom/matreshka#17]
Здравствуйте. Делаю рендеринг с помощью Handlebars, переназначая метод ```itemRenderer``` у коллекции (наследника ```MK.Array```). Из модели (наследник ```MK.Object```) вызываю событие ```rerender```, которое ловится коллекцией. Коллекция вызывает ```this.rerender()```, но ничего не происходит. ```this.processRendering()``` с разными аргументами тоже ничего не делают. Как сделать перерисовку шаблона из модели?

**Comment by finom** [comment]
Могу ли я попросить смоделировать баг на jsbin или на другом сервисе?
Матрешку можно подключить из cdn.
9 Июл 2015 г. 12:50 пользователь "Artur" <notifications@github.com> написал:

**Comment by atnartur** [comment]
JSBin: http://jsbin.com/muqilikezo/edit?html,js,output
Gist: https://gist.github.com/atnartur/33a8228f781e640d531f
Есть массив из трех объектов. В каждом объекте есть тип. Он меняется раз в 5 секунд. Значение, привязанное через bindNode меняется, а сам шаблон не перерисовывается, хотя событие вызывается (выводятся сообщения в консоль).

**Comment by finom** [comment]
Возможно, проблема в том, что вы ожидаете полной перерисовки. MK.Array
кеширует отрендеренные ноды а при вызове rerender "перевставляет" их.
Полная перерисовка нерациональна в большинстве случаев.
9 Июл 2015 г. 14:13 пользователь "Artur" <notifications@github.com> написал:

**Comment by atnartur** [comment]
Мне нужно сделать полную перерисовку только одной модели (объекта). Как это сделать?

**Comment by finom** [comment]
В текущей реализации прийдется вставить новый объект и удалить старый.

Сейчас у меня нет хорошего интернета и настольного компьютера под рукой.
Вот, предварительно работающий код:
index=arr.indexOf(object);
native=object.toJSON();
arr.pull(index);
arr.splice(index, 0, native);
Надеюсь, идея ясна.

Проблема интересная, займусь ей как приеду из отпуска.
9 Июл 2015 г. 14:31 пользователь "Artur" <notifications@github.com> написал:

**Comment by atnartur** [comment]
Огромное спасибо, заработало! Но это костыль, буду ждать решения в фреймворке:)

**Comment by finom** [comment]
https://trello.com/b/E5KcQESk/matreshka-js-features - добавил в туду.

**Comment by finom** [comment]
> Напишу сюда, наверняка читают. Есть идея сделать динамическую отрисовку по команде. Например, у меня есть рендерер itemRenderer = '<div></div>' и я хочу его заменить на itemRenderer = '<div><div></div></div>' (для примера). После замены рендерера на новый будет отрисовываться только новые элементы (весьма успешно и это радует), но при этом старые элементы отрисованы по-прежнему. Не изменяя данные модели, хотелось бы заставить объект перерисовать по команде узлы на новые. Это очень много где применимо на практике и чрезвычайно удобно. Добавьте, пожалуйста, такую функцию в матрёшку.

**Comment by finom** [comment]
1. В альфе появился флаг для rerender:
```
this.rerender({forceRerender: true});
```

2. При изменении itemRenderer, дерево перерисовывается. Останется ли эта фича, пока под вопросом, нужно погонять бенчмарками.

**Comment by matreshkajs** [comment]
Теперь можно написать this.itemRenderer =  "новое значение" и дерево перерисуется. Решено оставить, так как это никак не влияет на производительность.

**Comment by atnartur** [comment]
Спасибо!

**Comment by finom** [comment]
@atnartur новая версия в бранче develop пока что. Эта версия стабильна на 99%, поэтому релиз будет позже.

**Comment by atnartur** [comment]
```javascript
this.rerender({forceRerender: true});
```
работает! Спасибо! (версия 1.2.0)

**Comment by finom** [comment]
Пожалуйста :)

**Comment by atnartur** [comment]
Написал "спасибо", но в другом месте работает не так, как надо, оказывается. 
Нельзя ли сделать функцию ререндеринга только одного элемента массива? А то у меня ререндерится весь массив, и создается куча AJAX запросов, потому что каждый объект самостоятельно запрашивает часть данных. 

Сам пробовал - не получается:( processRendering у array только, а как реализовать хотя бы тот костыль в object - я не понял. 
Пока что оставляю тот костыль в своем проекте. Фича не срочная и очень специфическая. Если у Вас будет время, посмотрите еще раз пожалуйста эту проблему. Заранее спасибо!

**Comment by finom** [comment]
@atnartur  Вижу уведомление о сообщении, но сообщения не вижу. Вы его удалили?

**Comment by atnartur** [comment]
Удалил. Баг не подтвердился. Простите, что побеспокоил лишний раз:)

03.10.2015 21:16, Andrey Gubanov пишет:
